export const reviewDate = '2026-09-13';
export const sources = {
  containers: { title: 'MDN: cont&ecirc;ineres de m&iacute;dia', url: 'https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Containers' },
  codecs: { title: 'MDN: codecs de v&iacute;deo', url: 'https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Video_codecs' },
  conversion: { title: 'Mediabunny: convers&atilde;o e reempacotamento', url: 'https://mediabunny.dev/guide/converting-media-files' },
  reading: { title: 'Mediabunny: leitura de trilhas e metadados', url: 'https://mediabunny.dev/guide/reading-media-files' },
  sharing: { title: 'MDN: compartilhamento de arquivos', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share' },
  images: { title: 'MDN: formatos de imagem', url: 'https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Image_types' },
  files: { title: 'MDN: acesso a arquivos escolhidos pelo usu&aacute;rio', url: 'https://developer.mozilla.org/en-US/docs/Web/API/File_API' }
};
export const guides = [
  {
    slug: 'comprimir-video-com-qualidade', category: 'tamanho', categoryLabel: 'Tamanho &amp; envio', tool: 'comprimir-video', toolLabel: 'Comprimir v&iacute;deo', icon: 'minimize-2',
    title: 'Como reduzir o tamanho de um v&iacute;deo e avaliar a qualidade',
    summary: 'Uma c&oacute;pia menor s&oacute; ajuda se os detalhes importantes continuarem leg&iacute;veis.',
    image: 'compressor.jpg', caption: 'Interface atual do compressor com o v&iacute;deo de cinco segundos fornecido pelo respons&aacute;vel do site. O resultado varia conforme a entrada.',
    related: ['como-enviar-video-grande-no-whatsapp', 'mp4-mov-ou-webm'], sources: ['codecs', 'conversion'],
    sections: [
      { id: 'escolha', title: 'Comece pelo destino, n&atilde;o pela menor op&ccedil;&atilde;o', paragraphs: ['Um v&iacute;deo com letras pequenas precisa de outro cuidado que uma grava&ccedil;&atilde;o de paisagem. Antes de comprimir, decida o que o destinat&aacute;rio precisa enxergar: um rosto, uma placa, uma tela ou apenas a cena geral. Guarde o original fora da pasta de downloads para n&atilde;o confundir as duas vers&otilde;es.', 'Recodificar pode descartar detalhes. No teste inicial, use a qualidade Equilibrada e a altura m&aacute;xima de 720 px. A altura &eacute; um teto, n&atilde;o uma ordem para ampliar imagens menores. Se o resultado apagar informa&ccedil;&otilde;es importantes, experimente Mais detalhe antes de reduzir ainda mais a resolu&ccedil;&atilde;o.'] },
      { id: 'passos', title: 'Gere uma c&oacute;pia e compare', steps: ['Abra Comprimir v&iacute;deo e use Selecionar v&iacute;deo para escolher o original.', 'Em Qualidade da c&oacute;pia, escolha Equilibrada. Mantenha 720 px ou escolha 480 px se o destino n&atilde;o exigir detalhes pequenos.', 'Clique em Comprimir v&iacute;deo e aguarde MP4 validado. N&atilde;o feche a p&aacute;gina durante o processamento.', 'Alterne Original e Resultado. Confira os tamanhos medidos, reproduza a c&oacute;pia e s&oacute; ent&atilde;o use Baixar MP4.'] },
      { id: 'avaliacao', title: 'O que conferir na imagem', paragraphs: ['Pause uma cena com texto e outra com movimento. Observe bordas, rostos e objetos pequenos na mesma escala nas duas vers&otilde;es. Compare tamb&eacute;m uma parte escura: uma miniatura bonita n&atilde;o garante que o restante ficou aceit&aacute;vel.', 'Reproduza o in&iacute;cio, o meio e o fim com som. Verifique a orienta&ccedil;&atilde;o e se a fala acompanha o movimento da boca. A verifica&ccedil;&atilde;o autom&aacute;tica confirma que o arquivo &eacute; leg&iacute;vel, mas a import&acirc;ncia de cada detalhe depende do seu uso.'] },
      { id: 'maior', title: 'E se a c&oacute;pia ficar maior?', paragraphs: ['Isso aconteceu no teste com um original j&aacute; muito comprimido ao escolher Mais detalhe. O sistema informou N&atilde;o houve redu&ccedil;&atilde;o, em vez de esconder o crescimento. N&atilde;o substitua o original por uma c&oacute;pia maior apenas porque ela terminou de processar.', 'Para procurar outra combina&ccedil;&atilde;o, volte ao original e tente Mais leve ou 480 px. Evite comprimir a c&oacute;pia repetidamente: assim voc&ecirc; perde a refer&ecirc;ncia de qualidade. O limite inicial &eacute; 32 MiB, dois minutos e at&eacute; 1080p/60 fps; arquivos maiores precisam de outro fluxo.'] }
    ]
  },
  {
    slug: 'como-enviar-video-grande-no-whatsapp', category: 'tamanho', categoryLabel: 'Tamanho &amp; envio', tool: 'comprimir-video', toolLabel: 'Comprimir v&iacute;deo', icon: 'minimize-2',
    title: 'Como preparar um v&iacute;deo para compartilhar', summary: 'Reduza o peso quando necess&aacute;rio, baixe a c&oacute;pia e confira no destino.',
    image: 'compressor.jpg', caption: 'Compressor atual com a amostra de cinco segundos. O tamanho exibido corresponde ao arquivo gerado, n&atilde;o a uma promessa de envio.', related: ['comprimir-video-com-qualidade', 'como-cortar-video-no-celular'], sources: ['files', 'conversion'],
    sections: [
      { id: 'destino', title: 'Escolha o que precisa chegar a quem recebe', paragraphs: ['Antes de reduzir, decida se a pessoa precisa ler uma tela, reconhecer um rosto ou apenas acompanhar a cena. Confira as exig&ecirc;ncias do aplicativo de destino; este portal n&atilde;o define seus limites nem garante que ele aceitar&aacute; qualquer arquivo.', 'A ferramenta dedicada de envio foi retirada. O caminho atual &eacute; criar uma c&oacute;pia em Comprimir v&iacute;deo, baix&aacute;-la e anex&aacute;-la manualmente no aplicativo escolhido. O portal n&atilde;o acessa sua lista de contatos e n&atilde;o envia o v&iacute;deo por voc&ecirc;.'] },
      { id: 'passos', title: 'Prepare e baixe a c&oacute;pia', steps: ['Abra Comprimir v&iacute;deo e escolha o original em Selecionar v&iacute;deo.', 'Comece com Qualidade da c&oacute;pia em Equilibrada e Altura m&aacute;xima de 720 px. Use 480 px apenas se os detalhes continuarem suficientes.', 'Clique em Comprimir v&iacute;deo. Aguarde a valida&ccedil;&atilde;o e compare os tamanhos medidos de Original e Resultado.', 'Reproduza o resultado com som, use Baixar MP4 e anexe essa c&oacute;pia no aplicativo de destino.'] },
      { id: 'recebimento', title: 'Confira o arquivo que realmente chegou', paragraphs: ['Abra a c&oacute;pia baixada, n&atilde;o apenas a pr&eacute;via no site. Depois do envio, confira a vers&atilde;o recebida: alguns destinos modificam o arquivo. Compare orienta&ccedil;&atilde;o, textos pequenos, dura&ccedil;&atilde;o e &aacute;udio.', 'Um teste no Chrome/Windows n&atilde;o certifica todo celular ou aplicativo. Para uma grava&ccedil;&atilde;o importante, fa&ccedil;a primeiro um envio de teste e confirme a reprodu&ccedil;&atilde;o no aparelho que vai receber. Guarde o original separado da c&oacute;pia.'] },
      { id: 'ajuste', title: 'Se continuar grande ou perder detalhes', paragraphs: ['Se o resultado n&atilde;o ficar menor, o portal informa isso. Volte ao original e experimente Mais leve ou uma altura menor; n&atilde;o recomprima repetidamente a mesma c&oacute;pia. Se apenas parte da grava&ccedil;&atilde;o for necess&aacute;ria, Cortar v&iacute;deo permite escolher um intervalo.', 'N&atilde;o h&aacute; meta autom&aacute;tica de tamanho nesta vers&atilde;o. A entrada &eacute; limitada a 32 MiB, dois minutos e at&eacute; 1080p/60 fps, conforme o suporte do navegador. Arquivos maiores exigem outro fluxo, sem tentar contornar o limite renomeando o arquivo.'] }
    ]
  },
  {
    slug: 'como-converter-video-para-mp4', category: 'edicao', categoryLabel: 'Formato &amp; corte', tool: 'comprimir-video', toolLabel: 'Comprimir v&iacute;deo', icon: 'minimize-2', title: 'Como escolher qualidade e resolu&ccedil;&atilde;o do v&iacute;deo', summary: 'Escolha entre detalhe e tamanho sem ampliar uma imagem que j&aacute; &eacute; pequena.', image: 'compressor.jpg', caption: 'Controles atuais de qualidade e altura no compressor. A amostra tem cinco segundos e n&atilde;o determina o tamanho de outros resultados.', related: ['mp4-mov-ou-webm', 'comprimir-video-com-qualidade'], sources: ['codecs', 'conversion'],
    sections: [
      { id: 'controles', title: 'Qualidade e altura resolvem escolhas diferentes', paragraphs: ['O conversor dedicado foi retirado. Para reduzir o arquivo, use Comprimir v&iacute;deo: Mais leve prioriza uma c&oacute;pia menor, Equilibrada &eacute; um ponto de partida e Mais detalhe dedica mais dados &agrave; imagem. Nenhuma op&ccedil;&atilde;o recupera detalhes j&aacute; perdidos.', 'Altura m&aacute;xima limita a dimens&atilde;o de sa&iacute;da a 480, 720 ou 1080 px, respeitando a propor&ccedil;&atilde;o. &Eacute; um teto: selecionar 1080 px n&atilde;o amplia uma entrada menor. A c&oacute;pia &eacute; MP4 com H.264 e, quando existe som, AAC compat&iacute;vel.'] },
      { id: 'passos', title: 'Compare uma combina&ccedil;&atilde;o por vez', steps: ['Abra Comprimir v&iacute;deo, selecione o original e confira dimens&otilde;es e dura&ccedil;&atilde;o na an&aacute;lise.', 'Escolha Equilibrada em Qualidade da c&oacute;pia e 720 px em Altura m&aacute;xima para o primeiro teste.', 'Clique em Comprimir v&iacute;deo e aguarde o resultado validado. Reproduza uma cena com movimento e outra com detalhes pequenos.', 'Se necess&aacute;rio, volte ao original e altere uma op&ccedil;&atilde;o. Compare tamanho e imagem antes de Baixar MP4.'] },
      { id: 'comparacao', title: 'Mais pixels n&atilde;o garantem melhor imagem', paragraphs: ['Uma cena parada e uma com movimento podem reagir de forma diferente &agrave; mesma configura&ccedil;&atilde;o. Compare na escala em que a pessoa vai assistir. Se uma placa ou legenda perder legibilidade, tente Mais detalhe antes de diminuir a altura.', 'Confira v&iacute;deos verticais visualmente e reproduza com som. N&atilde;o escolha apenas pelo menor n&uacute;mero de bytes: orienta&ccedil;&atilde;o, sincronismo e detalhes &uacute;teis precisam continuar corretos. A verifica&ccedil;&atilde;o autom&aacute;tica n&atilde;o substitui essa compara&ccedil;&atilde;o.'] },
      { id: 'restricoes', title: 'O que esta escolha n&atilde;o faz', paragraphs: ['Mais detalhe pode gerar um arquivo maior que um original j&aacute; comprimido. O aviso de aus&ecirc;ncia de redu&ccedil;&atilde;o deve ser levado em conta. A ferramenta n&atilde;o oferece um modo geral de convers&atilde;o sem recompress&atilde;o nem conserta grava&ccedil;&otilde;es corrompidas.', 'O suporte &eacute; consultado no navegador antes da opera&ccedil;&atilde;o. Trilhas extras, HDR para recodifica&ccedil;&atilde;o e combina&ccedil;&otilde;es n&atilde;o homologadas podem ser recusados. Preserve o original e leia a mensagem espec&iacute;fica em vez de tentar resolver apenas trocando a extens&atilde;o.'] }
    ]
  },
  {
    slug: 'como-cortar-video-no-celular', category: 'edicao', categoryLabel: 'Formato &amp; corte', tool: 'cortar-video', toolLabel: 'Cortar v&iacute;deo', icon: 'scissors', title: 'Como cortar um v&iacute;deo no celular', summary: 'Defina um intervalo sem confundir corte de dura&ccedil;&atilde;o com recorte da imagem.', image: 'corte.jpg', caption: 'Controles atuais de intervalo, pr&eacute;via e qualidade, com a amostra de cinco segundos. A verifica&ccedil;&atilde;o em celular f&iacute;sico continua separada.', related: ['como-enviar-video-grande-no-whatsapp', 'como-capturar-imagem-de-video'], sources: ['conversion'],
    sections: [
      { id: 'intervalo', title: 'Aqui o corte &eacute; de tempo', paragraphs: ['Cortar v&iacute;deo conserva um trecho entre In&iacute;cio e Fim. N&atilde;o remove bordas, n&atilde;o muda o enquadramento e n&atilde;o oculta um rosto dentro da cena. Se voc&ecirc; precisa apagar uma informa&ccedil;&atilde;o que aparece na imagem, esta ferramenta n&atilde;o realiza essa edi&ccedil;&atilde;o.', 'Os campos usam segundos. Um in&iacute;cio de 1,23 e fim de 4,56 pede um trecho de aproximadamente 3,33 segundos. O m&iacute;nimo &eacute; 0,2 segundo, o fim precisa vir depois do in&iacute;cio e nenhum ponto pode ultrapassar a dura&ccedil;&atilde;o original.'] },
      { id: 'passos', title: 'Marque e experimente o trecho', steps: ['Abra Cortar v&iacute;deo e use Selecionar v&iacute;deo ou Usar v&iacute;deo de amostra.', 'Ajuste In&iacute;cio e Fim pelos campos em segundos ou pelos controles deslizantes. Tamb&eacute;m &eacute; poss&iacute;vel pausar o Original e usar Usar instante atual.', 'Confira a dura&ccedil;&atilde;o e clique em Reproduzir trecho: a pr&eacute;via para no fim escolhido. Defina Qualidade do trecho e Altura m&aacute;xima antes de Gerar trecho MP4.', 'Reproduza o Resultado, confira os primeiros e &uacute;ltimos quadros e o som. S&oacute; ent&atilde;o use Baixar c&oacute;pia.'] },
      { id: 'precisao', title: 'Precis&atilde;o e qualidade da c&oacute;pia', paragraphs: ['O corte recodifica o v&iacute;deo para n&atilde;o depender apenas dos pontos em que o original guardou um quadro completo. Ainda assim, o instante dispon&iacute;vel &eacute; limitado pelos quadros e pelos blocos de &aacute;udio. N&atilde;o trate um n&uacute;mero decimal como uma garantia de precis&atilde;o infinita.', 'Nos testes locais, o intervalo de 1,23 a 4,56 s gerou 3,33 s, com imagem inicial comparada &agrave; origem e sincronismo conferido. Um corte curto de 0,3 s em entrada sem som tamb&eacute;m passou. Isso n&atilde;o certifica todos os arquivos nem uma qualidade visual id&ecirc;ntica.'] },
      { id: 'celular', title: 'O que ainda depende do aparelho', paragraphs: ['Os controles foram testados em larguras de tela mobile emuladas no Chrome/Windows. Decodificadores, mem&oacute;ria e desempenho do celular real ainda precisam de verifica&ccedil;&atilde;o. Mantenha a p&aacute;gina aberta enquanto trabalha e use Cancelar se quiser interromper.', 'Para corrigir os pontos, volte &agrave; pr&eacute;via Original. Na pr&eacute;via Resultado, os controles de usar o instante ficam desabilitados para evitar confundir o tempo do trecho com o tempo da grava&ccedil;&atilde;o inteira. Preserve sempre o original e fa&ccedil;a um teste curto antes de uma edi&ccedil;&atilde;o importante.'] }
    ]
  },
  {
    slug: 'o-que-sao-metadados-de-video', category: 'privacidade', categoryLabel: 'Dados &amp; privacidade', tool: 'limpar-metadados-video', toolLabel: 'Inspecionar metadados de v&iacute;deo', icon: 'shield-check', title: 'O que os metadados de um v&iacute;deo podem revelar', summary: 'Separe campos descritivos, dados de reprodu&ccedil;&atilde;o e informa&ccedil;&otilde;es vis&iacute;veis na cena.', image: 'metadados.jpg', caption: 'Interface atual do limpador com campos descritivos fict&iacute;cios para demonstra&ccedil;&atilde;o. A amostra de cinco segundos n&atilde;o cont&eacute;m GPS de visitantes.', related: ['como-remover-metadados-de-video', 'como-compartilhar-videos-com-privacidade'], sources: ['reading'],
    sections: [
      { id: 'camadas', title: 'Nem todo dado tem o mesmo papel', paragraphs: ['A amostra atual tem cinco segundos e campos descritivos fict&iacute;cios adicionados para a demonstra&ccedil;&atilde;o; ela n&atilde;o cont&eacute;m GPS de um visitante. Arquivos de outras origens podem incluir localiza&ccedil;&atilde;o, autor, data e nome do programa. Esses campos s&atilde;o diferentes de resolu&ccedil;&atilde;o, codec, cor e rota&ccedil;&atilde;o usados na reprodu&ccedil;&atilde;o.', 'Existe ainda outra camada: o que a grava&ccedil;&atilde;o mostra e o que as pessoas falam. Uma placa de rua, um crach&aacute; ou um endere&ccedil;o dito em voz alta continua no conte&uacute;do mesmo quando um campo descritivo &eacute; removido.'] },
      { id: 'inspecao', title: 'Veja o que existe no seu arquivo', steps: ['Abra Limpar metadados de v&iacute;deo e selecione a grava&ccedil;&atilde;o.', 'Leia os valores e suas categorias: Localiza&ccedil;&atilde;o, Identifica&ccedil;&atilde;o, Data e hor&aacute;rio, Dispositivo ou programa, Conte&uacute;do descritivo e Campo n&atilde;o classificado.', 'O bot&atilde;o Selecionar dados pessoais e dispositivo marca as categorias recomendadas. Revise campo por campo antes de gerar: a classifica&ccedil;&atilde;o n&atilde;o garante identifica&ccedil;&atilde;o completa.', 'Diferencie datas descritivas de datas t&eacute;cnicas internas. Para remover, siga o guia de limpeza seletiva; apenas inspecionar n&atilde;o altera o original.'] },
      { id: 'ausencia', title: 'Uma lista vazia n&atilde;o prova aus&ecirc;ncia de dados', paragraphs: ['O leitor apresenta somente campos descritivos que consegue acessar. Um programa diferente pode interpretar campos propriet&aacute;rios que n&atilde;o aparecem aqui. A mensagem Nenhum campo descritivo acess&iacute;vel encontrado n&atilde;o &eacute; um certificado de anonimato.', 'Campos extensos ou numerosos demais geram uma recusa, em vez de uma lista resumida que pare&ccedil;a completa. No teste, aliases conhecidos n&atilde;o duplicaram a mesma informa&ccedil;&atilde;o na sele&ccedil;&atilde;o; campos desconhecidos acess&iacute;veis apareceram separadamente.'] },
      { id: 'decisao', title: 'Escolha o cuidado proporcional ao destino', paragraphs: ['Para compartilhar uma lembran&ccedil;a, talvez baste conferir localiza&ccedil;&atilde;o e autor. Para um material sens&iacute;vel, tamb&eacute;m revise o nome do arquivo, os quadros e o &aacute;udio. Se a consequ&ecirc;ncia de identifica&ccedil;&atilde;o for grave, n&atilde;o dependa s&oacute; deste limpador inicial.', 'A ferramenta trabalha localmente, mas isso n&atilde;o torna o dispositivo ou o destino automaticamente privados. O arquivo baixado pode ser sincronizado por outro aplicativo, e quem recebe pode encaminh&aacute;-lo. Inspe&ccedil;&atilde;o de metadados &eacute; uma etapa do cuidado, n&atilde;o toda a prote&ccedil;&atilde;o.'] }
    ]
  },
  {
    slug: 'como-remover-metadados-de-video', category: 'privacidade', categoryLabel: 'Dados &amp; privacidade', tool: 'limpar-metadados-video', toolLabel: 'Limpar metadados de v&iacute;deo', icon: 'shield-check', title: 'Como remover e conferir metadados de um v&iacute;deo', summary: 'Selecione os campos, gere outra c&oacute;pia e confira o que saiu e o que permaneceu.', image: 'metadados.jpg', caption: 'Interface atual do limpador com campos descritivos fict&iacute;cios para demonstra&ccedil;&atilde;o. A amostra de cinco segundos n&atilde;o cont&eacute;m GPS de visitantes.', related: ['o-que-sao-metadados-de-video', 'como-compartilhar-videos-com-privacidade'], sources: ['reading', 'conversion'],
    sections: [
      { id: 'suporte', title: 'Antes de come&ccedil;ar', paragraphs: ['A limpeza atual aceita MP4/MOV com imagem H.264 e, quando houver som, AAC compat&iacute;vel. Ela copia as trilhas sem recodific&aacute;-las. WebM, cap&iacute;tulos identificados e trilhas auxiliares n&atilde;o homologadas n&atilde;o entram nesse fluxo; n&atilde;o s&atilde;o descartados silenciosamente.', 'Guarde o original e decida quais valores precisam sair. Remover um autor n&atilde;o apaga direitos sobre o conte&uacute;do. Uma data t&eacute;cnica necess&aacute;ria ao cont&ecirc;iner tamb&eacute;m n&atilde;o deve ser confundida com a data descritiva escolhida na lista.'] },
      { id: 'passos', title: 'Limpeza seletiva, em uma c&oacute;pia', steps: ['Selecione o arquivo em Limpar metadados de v&iacute;deo e leia os valores e categorias dos campos encontrados.', 'Use Selecionar dados pessoais e dispositivo como ponto de partida. Revise a sele&ccedil;&atilde;o: t&iacute;tulos, coment&aacute;rios e campos n&atilde;o classificados exigem sua escolha manual; desmarque o que deseja manter.', 'Clique em Gerar c&oacute;pia e reinspecionar. Um campo escolhido que permane&ccedil;a ou um valor n&atilde;o escolhido que mude bloqueia a sa&iacute;da.', 'Leia Antes e depois da reinspe&ccedil;&atilde;o. Reproduza imagem e som, confira a orienta&ccedil;&atilde;o e use Baixar c&oacute;pia.'] },
      { id: 'exemplo', title: 'O exemplo seletivo foi conferido por outro leitor', paragraphs: ['No MOV de teste, a remo&ccedil;&atilde;o de Autor / artista manteve T&iacute;tulo privado. O teste completo escolheu tamb&eacute;m t&iacute;tulo, coment&aacute;rio, descri&ccedil;&atilde;o, data descritiva e localiza&ccedil;&atilde;o fict&iacute;cia. Um leitor independente conferiu a aus&ecirc;ncia dos valores escolhidos.', 'Os hashes de todos os pacotes codificados de v&iacute;deo e &aacute;udio permaneceram id&ecirc;nticos nesses exemplos. Isso mostra que essas trilhas n&atilde;o foram recomprimidas; n&atilde;o significa que o arquivo inteiro conserva o mesmo hash, pois o cont&ecirc;iner e seus campos mudaram.'] },
      { id: 'restante', title: 'O que permanece depois', paragraphs: ['Datas t&eacute;cnicas internas s&atilde;o recriadas pelo muxer e ficam na c&oacute;pia. Datas do sistema de arquivos podem mudar no download. Os limites de leitura tamb&eacute;m continuam: campos propriet&aacute;rios inacess&iacute;veis n&atilde;o foram certificados como removidos.', 'A imagem, as vozes, logotipos, placas e qualquer texto vis&iacute;vel permanecem. N&atilde;o h&aacute; altera&ccedil;&atilde;o de reconhecimento de conte&uacute;do nem promessa de anonimato. Se a interface recusar uma entrada, preserve-a e n&atilde;o interprete uma mensagem de erro como uma limpeza conclu&iacute;da.'] }
    ]
  },
  {
    slug: 'como-extrair-audio-de-video', category: 'audio-imagem', categoryLabel: '&Aacute;udio &amp; imagem', tool: 'extrair-audio', toolLabel: 'Extrair &aacute;udio', icon: 'audio-lines', title: 'Como extrair &aacute;udio de um v&iacute;deo', summary: 'Escolha WAV ou M4A e confira se a trilha inteira foi preservada.', image: 'audio.jpg', caption: 'Interface atual de extra&ccedil;&atilde;o com a amostra fornecida. WAV e M4A passaram nos testes locais; MP3 n&atilde;o est&aacute; habilitado.', related: ['mp4-mov-ou-webm', 'como-compartilhar-videos-com-privacidade'], sources: ['conversion'],
    sections: [
      { id: 'escolha', title: 'O formato precisa servir ao pr&oacute;ximo uso', paragraphs: ['WAV gera PCM 16-bit a 48 kHz nesta vers&atilde;o. Ele costuma ocupar mais espa&ccedil;o e &eacute; a op&ccedil;&atilde;o dispon&iacute;vel para quem precisa desse tipo de entrada em outro programa. Converter para WAV n&atilde;o recupera detalhes que o som original j&aacute; perdeu.', 'M4A guarda &aacute;udio AAC. Se a entrada j&aacute; tem AAC compat&iacute;vel, essa trilha &eacute; copiada sem recodifica&ccedil;&atilde;o. Outros codecs dependem do codificador dispon&iacute;vel no navegador. MP3 n&atilde;o &eacute; uma op&ccedil;&atilde;o da ferramenta: renomear um M4A como .mp3 n&atilde;o converte o som.'] },
      { id: 'passos', title: 'Separe a trilha', steps: ['Abra Extrair &aacute;udio e selecione o v&iacute;deo. Ou use a amostra para conhecer o fluxo sem arquivo pessoal.', 'Aguarde a an&aacute;lise. Uma entrada sem &aacute;udio informa essa condi&ccedil;&atilde;o e n&atilde;o libera uma trilha inventada.', 'Escolha WAV ou M4A em Formato de &aacute;udio e clique em Extrair &aacute;udio.', 'Reproduza o player de &aacute;udio do resultado, confira dura&ccedil;&atilde;o e use Baixar c&oacute;pia. Abra tamb&eacute;m no programa de destino.'] },
      { id: 'conferencia', title: 'Por que o &aacute;udio pode ser mais curto que o v&iacute;deo?', paragraphs: ['A verifica&ccedil;&atilde;o usa a dura&ccedil;&atilde;o da pr&oacute;pria trilha de &aacute;udio. Se o som termina antes da imagem, a extra&ccedil;&atilde;o pode ser mais curta sem estar incompleta. Se a trilha come&ccedil;a depois da imagem, o arquivo extra&iacute;do come&ccedil;a no primeiro som, sem acrescentar sil&ecirc;ncio para preencher esse atraso.', 'Escute o come&ccedil;o, uma parte intermedi&aacute;ria e o encerramento. Os testes locais inclu&iacute;ram &aacute;udio curto e com in&iacute;cio atrasado, al&eacute;m de WAV e M4A com decodifica&ccedil;&atilde;o completa. Isso verifica integridade t&eacute;cnica; n&atilde;o substitui escuta humana nem certifica todo aparelho.'] },
      { id: 'limites', title: 'Extra&ccedil;&atilde;o n&atilde;o isola uma voz', paragraphs: ['O resultado cont&eacute;m a trilha inteira, incluindo m&uacute;sica, ru&iacute;dos e conversas de fundo. N&atilde;o &eacute; separa&ccedil;&atilde;o de instrumentos, limpeza de ru&iacute;do nem transcri&ccedil;&atilde;o. O arquivo original fica intacto.', 'A entrada inicial aceita &aacute;udio mono ou est&eacute;reo, em uma &uacute;nica trilha. Se voc&ecirc; precisa escolher entre v&aacute;rios idiomas, trabalhar com multicanal ou arquivos longos, este fluxo ainda n&atilde;o foi homologado. Tamb&eacute;m revise nomes e endere&ccedil;os ditos em voz alta antes de compartilhar o &aacute;udio: retirar o v&iacute;deo n&atilde;o remove essas informa&ccedil;&otilde;es.'] }
    ]
  },
  {
    slug: 'como-capturar-imagem-de-video', category: 'audio-imagem', categoryLabel: '&Aacute;udio &amp; imagem', tool: 'capturar-miniatura', toolLabel: 'Capturar miniatura', icon: 'image', title: 'Como capturar uma imagem de um v&iacute;deo', summary: 'Encontre o quadro certo sem fotografar a tela nem distorcer a propor&ccedil;&atilde;o.', image: 'miniatura.jpg', caption: 'Controles atuais de instante e formato com o v&iacute;deo de cinco segundos. A imagem capturada respeita a orienta&ccedil;&atilde;o de exibi&ccedil;&atilde;o.', related: ['como-cortar-video-no-celular', 'como-compartilhar-videos-com-privacidade'], sources: ['images', 'reading'],
    sections: [
      { id: 'quadro', title: 'Escolha um instante, n&atilde;o uma tela', paragraphs: ['A ferramenta extrai o quadro do arquivo, sem incluir bot&otilde;es do player ou a interface do navegador. Voc&ecirc; escolhe um instante em segundos; o quadro dispon&iacute;vel segue a cad&ecirc;ncia do v&iacute;deo. Dois instantes muito pr&oacute;ximos podem corresponder &agrave; mesma imagem.', 'A propor&ccedil;&atilde;o e a rota&ccedil;&atilde;o de exibi&ccedil;&atilde;o s&atilde;o respeitadas, sem amplia&ccedil;&atilde;o, distor&ccedil;&atilde;o ou corte de bordas. Uma captura de imagem borrada continua borrada: o processo n&atilde;o inventa detalhes ausentes.'] },
      { id: 'passos', title: 'Capture e abra a imagem', steps: ['Abra Capturar miniatura e selecione o v&iacute;deo, ou use a amostra.', 'Pause o original numa cena e use Usar instante atual, ajuste o controle de tempo ou digite Instante (segundos).', 'Escolha PNG ou JPEG e clique em Capturar quadro. O instante precisa ser anterior ao fim do v&iacute;deo.', 'Confira a imagem apresentada, use Baixar c&oacute;pia e abra o arquivo fora do navegador para conferir dimens&otilde;es e orienta&ccedil;&atilde;o.'] },
      { id: 'formato', title: 'PNG ou JPEG?', paragraphs: ['PNG n&atilde;o aplica perdas adicionais de compress&atilde;o ao quadro extra&iacute;do. JPEG usa compress&atilde;o com perdas; a ferramenta usa qualidade 92%. Compare os arquivos quando a imagem tiver letras pequenas ou bordas de alto contraste.', 'Essa escolha n&atilde;o desfaz perdas do v&iacute;deo original nem garante que PNG ser&aacute; sempre menor. Se precisa enviar por outro aplicativo, confira os formatos aceitos e o tamanho real da imagem baixada. A captura n&atilde;o cria automaticamente uma capa com t&iacute;tulo ou elementos gr&aacute;ficos.'] },
      { id: 'exemplo', title: 'O teste com v&iacute;deo vertical', paragraphs: ['Num MOV girado, o PNG do instante 1 s manteve a exibi&ccedil;&atilde;o vertical de 360 &times; 640. Um JPEG de outro instante apresentou outro quadro. As duas imagens foram abertas e comparadas aos quadros da fonte por ferramenta independente.', 'O instante igual &agrave; dura&ccedil;&atilde;o total foi recusado, porque est&aacute; fora dos quadros existentes. Se houver erro ou formato sem suporte, n&atilde;o aparece uma imagem antiga como se fosse nova. Para conte&uacute;do sens&iacute;vel, revise toda a imagem antes de enviar: esta ferramenta n&atilde;o borra rostos nem apaga texto.'] }
    ]
  },
  {
    slug: 'mp4-mov-ou-webm', category: 'edicao', categoryLabel: 'Formato &amp; corte', tool: 'comprimir-video', toolLabel: 'Comprimir v&iacute;deo', icon: 'minimize-2', title: 'MP4, MOV e WebM: formato e codec n&atilde;o s&atilde;o a mesma coisa', summary: 'Entenda a an&aacute;lise da entrada e por que cada ferramenta aceita combina&ccedil;&otilde;es diferentes.', image: 'compressor.jpg', caption: 'An&aacute;lise e controles atuais do compressor com a amostra de cinco segundos. A extens&atilde;o n&atilde;o determina sozinha o suporte da entrada.', related: ['como-converter-video-para-mp4', 'como-extrair-audio-de-video'], sources: ['containers', 'codecs'],
    sections: [
      { id: 'diferenca', title: 'Leia as informa&ccedil;&otilde;es em conjunto', paragraphs: ['Um cont&ecirc;iner organiza imagem, &aacute;udio e outros dados no arquivo. O codec descreve como cada trilha foi codificada. Por isso, duas grava&ccedil;&otilde;es com extens&atilde;o .mp4 podem precisar de suportes diferentes no aparelho.', 'No portal, a an&aacute;lise apresenta formato, codec, dimens&otilde;es, dura&ccedil;&atilde;o e &aacute;udio. Leia esse conjunto antes de escolher uma opera&ccedil;&atilde;o. A extens&atilde;o ajuda a reconhecer o arquivo, mas n&atilde;o &eacute; uma verifica&ccedil;&atilde;o completa do conte&uacute;do.'] },
      { id: 'exemplos', title: 'O caminho depende da opera&ccedil;&atilde;o', table: { headers: ['Opera&ccedil;&atilde;o', 'Entrada e suporte', 'Sa&iacute;da atual'], rows: [['Comprimir ou cortar', 'Trilhas decodific&aacute;veis e codificador dispon&iacute;vel no navegador', 'MP4 com H.264 e AAC quando houver som'], ['Limpar metadados', 'MP4/MOV com H.264 e AAC compat&iacute;vel, quando houver som', 'C&oacute;pia MP4 sem recomprimir as trilhas'], ['Extrair &aacute;udio', 'Uma trilha mono/est&eacute;reo compat&iacute;vel com o formato escolhido', 'WAV ou M4A']] }, paragraphs: ['Esta tabela descreve os fluxos atuais, n&atilde;o uma garantia para todo arquivo. WebM n&atilde;o entra na limpeza de metadados; em outras opera&ccedil;&otilde;es depende do suporte consultado no navegador. O conversor dedicado n&atilde;o est&aacute; mais dispon&iacute;vel.'] },
      { id: 'decisao', title: 'Leia a an&aacute;lise antes de gerar', steps: ['Abra Comprimir v&iacute;deo e selecione a entrada original para consultar suas informa&ccedil;&otilde;es.', 'Leia formato, codec, dimens&otilde;es, dura&ccedil;&atilde;o e presen&ccedil;&atilde;o de &aacute;udio. Se houver uma recusa, confira o motivo.', 'Para uma c&oacute;pia menor, escolha qualidade e altura e use Comprimir v&iacute;deo. Para outro objetivo, abra a ferramenta correspondente no cat&aacute;logo.', 'Reproduza e baixe apenas a sa&iacute;da validada. Confira tamb&eacute;m no destino: funcionar no Chrome/Windows n&atilde;o garante todos os aparelhos.'] },
      { id: 'naofazer', title: 'O que trocar a extens&atilde;o n&atilde;o resolve', paragraphs: ['Mudar o nome pode fazer um programa procurar o leitor errado, sem alterar os bytes das trilhas. Isso n&atilde;o corrige um arquivo corrompido, n&atilde;o adiciona um codec ao navegador e n&atilde;o conserta &aacute;udio fora de sincronia.', 'Se a convers&atilde;o &eacute; recusada, conserve o original e leia a mensagem espec&iacute;fica. Este portal inicial n&atilde;o promete reparar grava&ccedil;&otilde;es danificadas, converter HDR sem mudan&ccedil;as ou preservar trilhas auxiliares n&atilde;o suportadas. A sa&iacute;da s&oacute; &eacute; liberada depois da verifica&ccedil;&atilde;o t&eacute;cnica; ainda cabe conferir se o conte&uacute;do atende ao seu uso.'] }
    ]
  },
  {
    slug: 'como-compartilhar-videos-com-privacidade', category: 'privacidade', categoryLabel: 'Dados &amp; privacidade', tool: 'limpar-metadados-video', toolLabel: 'Inspecionar metadados', icon: 'shield-check', title: 'Cuidados ao compartilhar v&iacute;deos com dados pessoais', summary: 'Revise o arquivo, a cena, o som e o destino. Uma limpeza isolada n&atilde;o cobre tudo.', image: 'metadados.jpg', caption: 'Interface atual do limpador com campos descritivos fict&iacute;cios para demonstra&ccedil;&atilde;o. A amostra de cinco segundos n&atilde;o cont&eacute;m GPS de visitantes.', related: ['o-que-sao-metadados-de-video', 'como-remover-metadados-de-video', 'como-capturar-imagem-de-video'], sources: ['files'],
    sections: [
      { id: 'cena', title: 'Comece pelo que qualquer pessoa consegue perceber', paragraphs: ['Assista &agrave; grava&ccedil;&atilde;o completa antes de compartilhar. Uma informa&ccedil;&atilde;o pode aparecer por um &uacute;nico instante: tela de conversa, documento sobre a mesa, placa de carro, rosto de outra pessoa ou indica&ccedil;&atilde;o de lugar. Pause os pontos duvidosos; n&atilde;o revise s&oacute; a capa.', 'Escute tamb&eacute;m conversas de fundo. Endere&ccedil;os, nomes e rotinas ditos em voz alta permanecem no som quando voc&ecirc; remove metadados. A ferramenta de captura pode ajudar a examinar um quadro, mas n&atilde;o oculta informa&ccedil;&otilde;es nem altera o original.'] },
      { id: 'arquivo', title: 'Confira nome e campos descritivos', steps: ['Use um nome de arquivo que n&atilde;o exponha um dado desnecess&aacute;rio. Renomear n&atilde;o modifica os metadados internos.', 'Inspecione os campos na ferramenta de metadados. Se o arquivo for compat&iacute;vel, escolha valores espec&iacute;ficos para remover.', 'Reinspecione a c&oacute;pia e confira o que ficou. Uma lista vazia n&atilde;o certifica campos que o leitor n&atilde;o consegue acessar.', 'Abra a c&oacute;pia exata que pretende enviar e revise imagem e &aacute;udio novamente. Guarde o original em local separado.'] },
      { id: 'destino', title: 'Escolha para quem e por qual caminho', paragraphs: ['Antes de enviar, confirme o contato ou grupo e se todas as pessoas precisam receber o arquivo completo. Uma miniatura tamb&eacute;m pode revelar dados; escolher uma imagem em vez do v&iacute;deo n&atilde;o elimina esse cuidado.', 'Um destinat&aacute;rio pode guardar ou encaminhar o material. O portal n&atilde;o controla o que acontece depois do download ou do compartilhamento. Se a exposi&ccedil;&atilde;o pode trazer uma consequ&ecirc;ncia grave, evite enviar at&eacute; ter um fluxo de revis&atilde;o adequado ao risco.'] },
      { id: 'local', title: 'Processamento local tem um escopo', paragraphs: ['Nesta implementa&ccedil;&atilde;o, o arquivo escolhido &eacute; lido no navegador e n&atilde;o &eacute; enviado a um servidor pelo motor. Os testes verificaram aus&ecirc;ncia de upload e telemetria de arquivo. Isso descreve o portal atual, n&atilde;o todo aplicativo instalado no aparelho.', 'O site precisa carregar seus pr&oacute;prios arquivos pela rede; uma pasta de downloads pode ser sincronizada por outro programa. N&atilde;o confunda processamento local com anonimato, dispositivo protegido ou aus&ecirc;ncia total de rede. Estas orienta&ccedil;&otilde;es s&atilde;o uma lista de cuidados, n&atilde;o uma certifica&ccedil;&atilde;o de seguran&ccedil;a pessoal.'] }
    ]
  }
];
