export const trustPages = [
  {
    slug: 'sobre', title: 'Sobre o HF Ferramentas', summary: 'Ferramentas de v&iacute;deo e guias para fazer escolhas conscientes sobre seus arquivos.',
    sections: [
      { id: 'projeto', title: 'O projeto', paragraphs: ['HF Ferramentas &eacute; um portal em desenvolvimento para comprimir, converter, cortar e inspecionar v&iacute;deos, separar &aacute;udio e capturar imagens. O respons&aacute;vel p&uacute;blico &eacute; <strong>HF NEW DIGITAL</strong>. O atendimento informado &eacute; <a href="../contato/index.html">contato@hfnew.com.br</a>.', 'A proposta &eacute; realizar as opera&ccedil;&otilde;es suportadas no navegador, sem enviar o arquivo escolhido ao motor de um servidor. As ferramentas preservam o original e geram uma c&oacute;pia; cada resultado precisa ser conferido para o uso pretendido.'] },
      { id: 'conteudo', title: 'Guias e exemplos', paragraphs: ['A central tem dez guias ligados aos controles reais das ferramentas. Textos elaborados com assist&ecirc;ncia de IA (Codex) informam essa autoria e a pend&ecirc;ncia de revis&atilde;o editorial humana. N&atilde;o apresentamos um texto automatizado como revis&atilde;o de um especialista humano.', 'Capturas e resultados num&eacute;ricos s&atilde;o exemplos locais do projeto. Amostras sint&eacute;ticas e materiais com origem autorizada n&atilde;o representam todos os v&iacute;deos. Os exemplos de metadados usam valores fict&iacute;cios, n&atilde;o arquivos de visitantes.'] },
      { id: 'estado', title: 'O que est&aacute; em teste', paragraphs: ['Esta vers&atilde;o &eacute; uma pr&eacute;via local, ainda sem publica&ccedil;&atilde;o do novo portal no dom&iacute;nio. Chrome/Windows e larguras de tela emuladas foram testados. Celulares f&iacute;sicos, envio pelo WhatsApp e outros navegadores n&atilde;o est&atilde;o homologados.', 'N&atilde;o h&aacute; promessa de compress&atilde;o sem perdas, arquivos ilimitados ou remo&ccedil;&atilde;o universal de metadados. <a href="../seguranca-e-processamento-local/index.html">Conhe&ccedil;a o escopo do processamento local</a> antes de usar material sens&iacute;vel.'] }
    ], image: true
  },
  {
    slug: 'contato', title: 'Contato', summary: 'Fale com HF NEW DIGITAL sobre as ferramentas, os guias ou seus dados.', contact: true,
    sections: [
      { id: 'assuntos', title: 'Como podemos receber sua solicita&ccedil;&atilde;o', paragraphs: ['Use o e-mail p&uacute;blico para informar um problema t&eacute;cnico, sugerir uma corre&ccedil;&atilde;o nos guias, tratar de privacidade ou apontar conte&uacute;do que possa afetar direitos autorais. HF NEW DIGITAL confirmou que essa caixa existe e recebe mensagens.', 'O link abre o seu aplicativo de e-mail com o destinat&aacute;rio indicado. Voc&ecirc; revisa e envia por esse aplicativo; esta p&aacute;gina n&atilde;o transmite uma mensagem nem confirma entrega. Se n&atilde;o houver aplicativo configurado, use o endere&ccedil;o no seu webmail.'] },
      { id: 'informacoes', title: 'Envie somente o necess&aacute;rio', list: ['Informe o nome da ferramenta, o navegador e a mensagem de erro.', 'Descreva o problema sem anexar o v&iacute;deo pessoal. Se uma captura ajudar, remova dados que n&atilde;o sejam necess&aacute;rios.', 'Para um pedido de privacidade, explique a rela&ccedil;&atilde;o com o portal e o que deseja verificar.', 'Para direitos autorais, indique o endere&ccedil;o da p&aacute;gina, o material e a rela&ccedil;&atilde;o com o direito alegado.'] },
      { id: 'segredos', title: 'N&atilde;o envie credenciais', paragraphs: ['N&atilde;o envie senha, c&oacute;digo de acesso, documento completo ou dados banc&aacute;rios. Caso uma informa&ccedil;&atilde;o adicional seja necess&aacute;ria para compreender a solicita&ccedil;&atilde;o, ela deve ser limitada a esse objetivo.', 'N&atilde;o anunciamos prazo fixo ou atendimento 24 horas. O tratamento da correspond&ecirc;ncia usa seu aplicativo e o provedor de e-mail; veja o <a href="../privacidade/index.html">aviso de privacidade</a>.'] }
    ]
  },
  {
    slug: 'privacidade', title: 'Privacidade', summary: 'O que esta pr&eacute;via processa no navegador e o que acontece quando voc&ecirc; entra em contato.',
    sections: [
      { id: 'responsavel', title: 'Respons&aacute;vel e escopo', paragraphs: ['O respons&aacute;vel p&uacute;blico pelo HF Ferramentas &eacute; HF NEW DIGITAL. Solicita&ccedil;&otilde;es sobre dados podem ser encaminhadas a <a href="mailto:contato@hfnew.com.br">contato@hfnew.com.br</a>. Este aviso descreve a pr&eacute;via local atual, n&atilde;o uma configura&ccedil;&atilde;o de hospedagem futura.', 'As ferramentas n&atilde;o exigem cadastro. Esta vers&atilde;o n&atilde;o possui checkout, captura de leads, GA/GTM, publicidade ativa ou conex&atilde;o n8n. Qualquer inclus&atilde;o futura precisa de nova verifica&ccedil;&atilde;o e atualiza&ccedil;&atilde;o deste aviso antes de ser habilitada.'] },
      { id: 'arquivos', title: 'Arquivos escolhidos', paragraphs: ['V&iacute;deo, nome do arquivo, trilhas e metadados acess&iacute;veis s&atilde;o lidos no navegador para a opera&ccedil;&atilde;o escolhida. O motor n&atilde;o envia esses arquivos, imagens ou valores a um servidor nem a analytics. Os dados necess&aacute;rios ficam em mem&oacute;ria durante o trabalho.', 'Troca de arquivo, reset e sa&iacute;da da p&aacute;gina encerram os trabalhos e revogam as URLs locais administradas pela interface. Isso n&atilde;o &eacute; uma promessa de apagamento forense do dispositivo. Uma c&oacute;pia baixada fica na pasta escolhida pelo navegador; sua exclus&atilde;o e eventual sincroniza&ccedil;&atilde;o dependem do aparelho e de outros aplicativos.'] },
      { id: 'rede', title: 'Rede, armazenamento e acesso', paragraphs: ['O navegador carrega HTML, estilos, fontes, &iacute;cones, scripts e amostras do pr&oacute;prio portal. Processar localmente n&atilde;o significa navegar sem rede. No servidor da pr&eacute;via, os endere&ccedil;os permitidos s&atilde;o somente de leitura; n&atilde;o h&aacute; rota de upload ou grava&ccedil;&atilde;o de arquivo pessoal.', 'N&atilde;o h&aacute; log persistente de requisi&ccedil;&otilde;es por visitante implementado no servidor de pr&eacute;via. O endere&ccedil;o de rede e a requisi&ccedil;&atilde;o ainda s&atilde;o necess&aacute;rios para a conex&atilde;o. Logs, provedores e reten&ccedil;&atilde;o da futura hospedagem precisam ser confirmados antes da publica&ccedil;&atilde;o. <a href="../cookies/index.html">Veja tamb&eacute;m cookies e armazenamento</a>.'] },
      { id: 'mensagens', title: 'Mensagens de atendimento', paragraphs: ['Ao enviar e-mail por escolha pr&oacute;pria, seu endere&ccedil;o, mensagem e eventuais anexos passam pelo seu servi&ccedil;o de e-mail e pelo provedor da caixa de atendimento. Esse &eacute; um fluxo diferente do processamento local das ferramentas. Evite anexos sens&iacute;veis e envie apenas o necess&aacute;rio para tratar a solicita&ccedil;&atilde;o.', 'A defini&ccedil;&atilde;o documental da finalidade, base legal, acesso e reten&ccedil;&atilde;o dessas mensagens ainda precisa da revis&atilde;o de HF NEW DIGITAL antes de o aviso ser tratado como pol&iacute;tica definitiva de produ&ccedil;&atilde;o. N&atilde;o afirmamos um prazo de exclus&atilde;o que n&atilde;o foi confirmado.'] },
      { id: 'direitos', title: 'Solicita&ccedil;&otilde;es sobre dados', paragraphs: ['Conforme a legisla&ccedil;&atilde;o aplic&aacute;vel, podem existir direitos de confirma&ccedil;&atilde;o do tratamento, acesso, corre&ccedil;&atilde;o e outros previstos na LGPD. Encaminhe sua solicita&ccedil;&atilde;o ao contato p&uacute;blico. A identifica&ccedil;&atilde;o necess&aacute;ria para responder deve ser proporcional ao pedido, sem solicitar credenciais.', 'Este texto n&atilde;o certifica adequa&ccedil;&atilde;o jur&iacute;dica integral. Refer&ecirc;ncia: <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm">LGPD, especialmente os direitos do titular no artigo 18</a>.'] }
    ]
  },
  {
    slug: 'termos', title: 'Termos de uso', summary: 'Condi&ccedil;&otilde;es t&eacute;cnicas e cuidados para usar esta vers&atilde;o de testes.',
    sections: [
      { id: 'servico', title: 'Finalidade e estado do servi&ccedil;o', paragraphs: ['HF Ferramentas, sob responsabilidade p&uacute;blica de HF NEW DIGITAL, oferece uma pr&eacute;via local de ferramentas de v&iacute;deo e guias. N&atilde;o h&aacute; cobran&ccedil;a, conta de usu&aacute;rio ou promessa de disponibilidade cont&iacute;nua nesta implementa&ccedil;&atilde;o.', 'Use somente materiais que voc&ecirc; possa tratar e compartilhar legitimamente. O portal n&atilde;o verifica a titularidade de cada arquivo e n&atilde;o transfere direitos sobre ele ao converter, cortar ou remover campos descritivos.'] },
      { id: 'limites', title: 'Limites de processamento', paragraphs: ['O limite inicial &eacute; 32 MiB de entrada, 120 segundos, at&eacute; 1080p/60 fps, uma trilha de v&iacute;deo e no m&aacute;ximo uma de &aacute;udio mono/est&eacute;reo. A sa&iacute;da tem teto de 48 MiB e o trabalho tem prazo de 180 segundos. Formatos e codecs dependem do suporte real do navegador.', 'HDR para recodifica&ccedil;&atilde;o, trilhas auxiliares e outros casos n&atilde;o homologados podem ser recusados. Uma recusa n&atilde;o libera um upload alternativo. Metas de tamanho n&atilde;o garantem um tamanho exato nem envio por um aplicativo externo.'] },
      { id: 'resultado', title: 'Confira a c&oacute;pia e preserve o original', paragraphs: ['O original n&atilde;o &eacute; substitu&iacute;do pela interface. Antes de usar a sa&iacute;da, confira dura&ccedil;&atilde;o, imagem, som, orienta&ccedil;&atilde;o e tamanho. Recodifica&ccedil;&atilde;o pode mudar a qualidade. Metadados removidos n&atilde;o tornam o conte&uacute;do an&ocirc;nimo.', 'Os testes realizados no Chrome/Windows n&atilde;o homologam todos os aparelhos ou arquivos. Guias elaborados com assist&ecirc;ncia de IA t&ecirc;m revis&atilde;o editorial humana pendente. N&atilde;o dependa exclusivamente desta pr&eacute;via para material insubstitu&iacute;vel ou sens&iacute;vel.'] },
      { id: 'direitos', title: 'Contato e direitos aplic&aacute;veis', paragraphs: ['Relate falhas ou d&uacute;vidas pelo <a href="../contato/index.html">contato p&uacute;blico</a>. Usar um arquivo na ferramenta n&atilde;o representa autoriza&ccedil;&atilde;o para publicidade ou coleta futura de dados.', 'Estes termos n&atilde;o afastam direitos garantidos pela legisla&ccedil;&atilde;o aplic&aacute;vel nem estabelecem ren&uacute;ncia geral de responsabilidade. Condi&ccedil;&otilde;es jur&iacute;dicas definitivas precisam de revis&atilde;o antes da publica&ccedil;&atilde;o em produ&ccedil;&atilde;o.'] }
    ]
  },
  {
    slug: 'cookies', title: 'Cookies e armazenamento', summary: 'Entenda o uso de mem&oacute;ria e os recursos do navegador nesta vers&atilde;o do portal.',
    sections: [
      { id: 'atual', title: 'O que est&aacute; implementado agora', paragraphs: ['Esta pr&eacute;via n&atilde;o implementa cookies de autentica&ccedil;&atilde;o, medi&ccedil;&atilde;o ou publicidade. N&atilde;o grava arquivos ou prefer&ecirc;ncias em localStorage, sessionStorage ou IndexedDB. Os controles e resultados usam o estado da p&aacute;gina e sua mem&oacute;ria tempor&aacute;ria.', 'O servidor da pr&eacute;via n&atilde;o envia Set-Cookie nas respostas previstas. Fontes e scripts s&atilde;o servidos pelo pr&oacute;prio portal. N&atilde;o h&aacute; GA/GTM, pixels de marketing ou AdSense ativo nesta vers&atilde;o.'] },
      { id: 'diferencas', title: 'Mem&oacute;ria n&atilde;o &eacute; toda a atividade do navegador', paragraphs: ['O navegador pode manter hist&oacute;rico, cache ou downloads segundo suas configura&ccedil;&otilde;es. Esses mecanismos n&atilde;o equivalem a um cookie criado por esta p&aacute;gina. Links externos abertos por voc&ecirc; passam a seguir as regras dos outros sites.', 'N&atilde;o h&aacute; recursos opcionais de rastreamento habilitados nesta vers&atilde;o. A aus&ecirc;ncia de cookies n&atilde;o dispensa a verifica&ccedil;&atilde;o das demais obriga&ccedil;&otilde;es de privacidade.'] },
      { id: 'mudancas', title: 'Antes de habilitar recursos opcionais', paragraphs: ['Qualquer medi&ccedil;&atilde;o ou publicidade futura precisa de revis&atilde;o de finalidade, fornecedores, armazenamento e requisitos aplic&aacute;veis de consentimento. A p&aacute;gina deve ser atualizada e os controles necess&aacute;rios devem funcionar de verdade antes da ativa&ccedil;&atilde;o.', 'Refer&ecirc;ncia de transpar&ecirc;ncia: <a href="https://www.gov.br/anpd/pt-br/assuntos/noticias-periodo-eleitoral/anpd-lanca-guia-orientativo-201ccookies-e-protecao-de-dados-pessoais201d">orienta&ccedil;&otilde;es da ANPD sobre cookies e prote&ccedil;&atilde;o de dados</a>. D&uacute;vidas podem ser enviadas a <a href="../contato/index.html">HF NEW DIGITAL</a>.'] }
    ]
  },
  {
    slug: 'direitos-autorais', title: 'Direitos autorais', summary: 'Uma altera&ccedil;&atilde;o t&eacute;cnica do arquivo n&atilde;o muda automaticamente seus direitos de uso.',
    sections: [
      { id: 'materiais', title: 'Arquivos tratados por voc&ecirc;', paragraphs: ['Converter, cortar, extrair &aacute;udio ou capturar um quadro n&atilde;o concede autoriza&ccedil;&atilde;o para publicar o conte&uacute;do. Use materiais pr&oacute;prios ou com direitos e permiss&otilde;es adequados ao uso pretendido. A exist&ecirc;ncia de uma ferramenta n&atilde;o substitui essa verifica&ccedil;&atilde;o.', 'A limpeza de autor, t&iacute;tulo ou outros campos descritivos n&atilde;o apaga direitos autorais e n&atilde;o altera reconhecimento de conte&uacute;do. A interface n&atilde;o serve para contornar prote&ccedil;&otilde;es ou buscar uma declara&ccedil;&atilde;o de que o arquivo ficou livre de direitos.'] },
      { id: 'portal', title: 'Bibliotecas, fontes e amostras do portal', paragraphs: ['O motor utiliza <a href="../_portal/engine/mediabunny-LICENSE.txt">Mediabunny 1.56.2 sob MPL-2.0</a>; <a href="../_portal/manrope-OFL.txt">fontes Manrope</a> e <a href="../_portal/lucide-LICENSE.txt">&iacute;cones Lucide</a> mant&ecirc;m seus avisos de licen&ccedil;a. Essas licen&ccedil;as n&atilde;o s&atilde;o substitu&iacute;das por uma declara&ccedil;&atilde;o gen&eacute;rica de propriedade sobre todo o site.', 'A amostra floral foi usada com origem CC0 documentada no projeto; o exemplo adicional usa &aacute;udio sint&eacute;tico e metadados fict&iacute;cios. Capturas dos guias s&atilde;o testes locais, sem arquivos de visitantes. Textos elaborados com assist&ecirc;ncia de IA t&ecirc;m essa autoria indicada, sem promessa de exclusividade jur&iacute;dica n&atilde;o verificada.'] },
      { id: 'solicitacao', title: 'Informe um poss&iacute;vel problema', paragraphs: ['Escreva para <a href="mailto:contato@hfnew.com.br">contato@hfnew.com.br</a> e indique o endere&ccedil;o da p&aacute;gina, o material questionado, a rela&ccedil;&atilde;o com o direito alegado e um contato para resposta. N&atilde;o envie senha ou documentos completos para iniciar a conversa.', 'HF NEW DIGITAL &eacute; o respons&aacute;vel p&uacute;blico pelo portal. A an&aacute;lise de uma solicita&ccedil;&atilde;o deve considerar o contexto e a legisla&ccedil;&atilde;o aplic&aacute;vel; n&atilde;o prometemos uma decis&atilde;o autom&aacute;tica. Refer&ecirc;ncia brasileira: <a href="https://www.planalto.gov.br/ccivil_03/leis/l9610.htm">Lei n&ordm; 9.610/1998</a>.'] }
    ]
  },
  {
    slug: 'seguranca-e-processamento-local', title: 'Seguran&ccedil;a e processamento local', summary: 'Onde o trabalho acontece, quais s&atilde;o seus limites e o que continua sob seu cuidado.',
    sections: [
      { id: 'fluxo', title: 'O caminho do arquivo', paragraphs: ['Depois da sele&ccedil;&atilde;o, o navegador l&ecirc; a entrada e executa o motor em um worker local. A ferramenta permite um trabalho por vez, informa progresso real e s&oacute; libera a sa&iacute;da ap&oacute;s verificar formato e legibilidade. N&atilde;o h&aacute; upload alternativo quando o suporte local falha.', 'A entrada n&atilde;o &eacute; sobrescrita. O resultado &eacute; um Blob em mem&oacute;ria, acessado por uma URL local e baixado somente quando voc&ecirc; escolhe. Refer&ecirc;ncia t&eacute;cnica: <a href="https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static">URLs de objetos no navegador</a>.'] },
      { id: 'recursos', title: 'Cancelar, trocar ou sair', paragraphs: ['Cancelar termina o worker e impede que respostas atrasadas substituam o estado atual. Trocar o arquivo, usar reset ou sair da p&aacute;gina revoga as URLs locais administradas pelo portal. Uma c&oacute;pia j&aacute; baixada n&atilde;o &eacute; exclu&iacute;da por essas a&ccedil;&otilde;es.', 'Limites de tamanho, dura&ccedil;&atilde;o, resolu&ccedil;&atilde;o, canais de &aacute;udio e tempo de trabalho reduzem a carga inicial, mas n&atilde;o garantem que qualquer aparelho tenha mem&oacute;ria suficiente. Os testes atuais s&atilde;o do Chrome/Windows; outros ambientes e celulares reais ainda precisam de valida&ccedil;&atilde;o.'] },
      { id: 'metadados', title: 'Limpeza n&atilde;o &eacute; anonimiza&ccedil;&atilde;o', paragraphs: ['O limpador trata campos descritivos acess&iacute;veis em entradas compat&iacute;veis. Campos selecionados s&atilde;o removidos e a c&oacute;pia &eacute; reinspecionada; um campo n&atilde;o escolhido que mude bloqueia o resultado. Datas t&eacute;cnicas internas s&atilde;o recriadas e permanecem.', 'Campos propriet&aacute;rios n&atilde;o lidos, texto na imagem, vozes, faces e dados de contexto podem identificar algu&eacute;m. Direitos autorais e reconhecimento de conte&uacute;do n&atilde;o s&atilde;o removidos. N&atilde;o fornecemos certificado de anonimato ou de remo&ccedil;&atilde;o total de dados.'] },
      { id: 'cuidados', title: 'Aparelho, downloads e destino', paragraphs: ['Mantenha o navegador atualizado, preserve o original e confira imagem e som da c&oacute;pia. Evite arquivos de origem duvidosa e n&atilde;o dependa somente desta pr&eacute;via para material sens&iacute;vel ou insubstitu&iacute;vel.', 'Hist&oacute;rico, cache, extens&otilde;es, sincroniza&ccedil;&atilde;o de pastas e aplicativos de envio est&atilde;o fora do controle deste motor. Processamento local n&atilde;o garante um aparelho protegido nem aus&ecirc;ncia total de rede. Para relatar uma falha, use o <a href="../contato/index.html">contato p&uacute;blico</a> sem anexar um v&iacute;deo pessoal por padr&atilde;o.'] }
    ]
  }
];
