import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { guides, sources, reviewDate } from '../src/guides/content.mjs';
import { publicFooter } from '../src/shared/footer.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { routes } = JSON.parse(fs.readFileSync(path.join(root, '.portal-planejamento/rotas.json'), 'utf8'));
const attr = value => String(value).replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const write = (file, content) => { fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true }); fs.writeFileSync(path.join(root, file), content); };
const icon = (base, name) => `<img src="${base}_portal/icons/${name}.svg" width="18" height="18" alt="">`;
const assets = new Set(guides.map(guide => guide.image));
// Captures are reviewed assets: rebuilding text must never restore old screenshots.
for (const name of assets) {
  if (!/^[a-z-]+\.jpg$/.test(name) || !fs.existsSync(path.join(root, '_portal/guides', name))) throw new Error(`Captura atual ausente: ${name}`);
}
const displayDate = reviewDate.split('-').reverse().join('/');
function shell(title, description, url, base, body, hub = false) {
  return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><meta name="portal-stage" content="7"><meta name="description" content="${attr(description)}"><title>${title} | HF Ferramentas</title><link rel="canonical" href="https://www.hfnew.com.br${url}"><link rel="icon" href="${base}_portal/clapperboard.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}_portal/base.css"><link rel="stylesheet" href="${base}_portal/guides.css"><link rel="stylesheet" href="${base}_portal/footer.css">${hub ? `<script defer src="${base}_portal/guides.js"></script>` : ''}</head>
<body class="guides-page"><a class="skip" href="#conteudo">Ir para o conte&uacute;do</a><header><div class="header-inner"><a class="brand" href="${base}index.html"><span class="brand-mark">hf<span>.</span></span><span class="brand-name">Ferramentas<span class="brand-sub">V&Iacute;DEO &amp; &Aacute;UDIO</span></span></a><nav class="guide-nav" aria-label="Principal"><a href="${base}index.html#ferramentas">Ferramentas</a><a href="${hub ? 'index.html' : '../index.html'}" aria-current="${hub ? 'page' : 'location'}">Guias</a></nav><span class="preview-label">Pr&eacute;via</span></div></header>
${body}${publicFooter(base)}</body></html>\n`;
}
const sectionHtml = section => `<section id="${section.id}" class="article-section"><h2>${section.title}</h2>${(section.paragraphs || []).map(p => `<p>${p}</p>`).join('')}${section.steps ? `<ol class="procedure">${section.steps.map(step => `<li>${step}</li>`).join('')}</ol>` : ''}${section.table ? `<div class="table-wrap"><table><thead><tr>${section.table.headers.map(h => `<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${section.table.rows.map(row => `<tr>${row.map(value => `<td>${value}</td>`).join('')}</tr>`).join('')}</tbody></table></div>` : ''}</section>`;
const bySlug = new Map(guides.map(guide => [guide.slug, guide]));
for (const guide of guides) {
  const route = routes.find(route => route.url === `/guias/${guide.slug}/`);
  if (!route || !routes.some(item => item.group === 'tool' && item.url === `/${guide.tool}/`) || guide.related.some(slug => !bySlug.has(slug)) || guide.sources.some(key => !sources[key])) throw new Error(`Inventario invalido: ${guide.slug}`);
  const words = JSON.stringify(guide.sections).replace(/&[^;]+;/g, 'x').split(/\s+/).length;
  const minutes = Math.max(2, Math.ceil(words / 180));
  const body = `<main id="conteudo" class="guide-container" tabindex="-1"><nav class="breadcrumbs" aria-label="Caminho"><a href="../../index.html">In&iacute;cio</a><span aria-hidden="true">/</span><a href="../index.html">Guias</a><span aria-hidden="true">/</span><span>${guide.categoryLabel}</span></nav>
<div class="reading-layout"><article><header class="article-heading"><p class="guide-kicker">${guide.categoryLabel}</p><h1>${guide.title}</h1><p class="article-summary">${guide.summary}</p><div class="article-meta"><span>${minutes} min de leitura</span><time datetime="${reviewDate}">Atualizado em ${displayDate}</time></div><p class="authorship">Elabora&ccedil;&atilde;o: Codex (assistente de IA). Revis&atilde;o editorial humana: pendente.</p></header>
${guide.sections.map((section, index) => sectionHtml(section) + (index === 1 ? `<figure class="guide-example"><a href="../../_portal/guides/${guide.image}" aria-label="Abrir captura da ferramenta em tamanho completo"><img src="../../_portal/guides/${guide.image}" alt="Captura real da ferramenta: ${attr(guide.toolLabel)}" loading="lazy" width="1200" height="900"></a><figcaption>${guide.caption}</figcaption></figure>` : '')).join('')}
<section class="article-section test-scope" id="validacao"><h2>Escopo da verifica&ccedil;&atilde;o</h2><p>Procedimentos conferidos nos controles atuais e testes locais do Chrome/Windows. Viewports mobile s&atilde;o emulados; aparelhos f&iacute;sicos e outros navegadores n&atilde;o est&atilde;o homologados. Exemplos e capturas s&atilde;o do projeto, com amostras sint&eacute;ticas ou autorizadas, sem dados de visitantes.</p></section>
<section class="article-section" id="fontes"><h2>Fontes t&eacute;cnicas</h2><ul class="source-list">${guide.sources.map(key => `<li><a href="${sources[key].url}" rel="noopener noreferrer">${sources[key].title}</a></li>`).join('')}</ul><p class="source-note">Refer&ecirc;ncias da implementa&ccedil;&atilde;o. Resultados num&eacute;ricos e limites do portal v&ecirc;m dos testes locais, n&atilde;o de uma garantia das fontes.</p></section>
<section class="article-section" id="relacionados"><h2>Continue por aqui</h2><ul class="related-guides">${guide.related.map(slug => `<li><a href="../${slug}/index.html">${bySlug.get(slug).title}${icon('../../', 'arrow-right')}</a></li>`).join('')}</ul></section></article>
<aside class="reading-sidebar"><nav aria-label="Neste guia"><h2>Neste guia</h2>${guide.sections.map(section => `<a href="#${section.id}">${section.title}</a>`).join('')}<a href="#fontes">Fontes t&eacute;cnicas</a></nav><div class="tool-shortcut"><span>Ferramenta relacionada</span><a href="../../${guide.tool}/index.html">${icon('../../', guide.icon)}${guide.toolLabel}${icon('../../', 'arrow-up-right')}</a><p>Processamento local. O original n&atilde;o &eacute; substitu&iacute;do.</p></div></aside></div></main>`;
  write(route.file, shell(guide.title, guide.summary, route.url, '../../', body));
}
const hub = `<main id="conteudo" class="guide-container" tabindex="-1"><nav class="breadcrumbs" aria-label="Caminho"><a href="../index.html">In&iacute;cio</a><span aria-hidden="true">/</span><span>Guias</span></nav><div class="hub-heading"><p class="guide-kicker">ARQUIVOS, ESCOLHAS E CUIDADOS</p><h1>Guias de v&iacute;deo</h1><p>Do arquivo original &agrave; c&oacute;pia que voc&ecirc; quer compartilhar.</p></div>
<div class="guide-toolbar"><div class="guide-search" hidden>${icon('../', 'search')}<input type="search" id="guide-search" aria-label="Buscar guia" placeholder="Buscar por assunto" autocomplete="off"><button type="button" id="guide-clear" title="Limpar busca" aria-label="Limpar busca" hidden>${icon('../', 'x')}</button></div><span id="guide-count" role="status" aria-live="polite">10 guias</span></div><div class="guide-filters" role="group" aria-label="Categorias dos guias" hidden>${[['all','Todos'], ['tamanho','Tamanho &amp; envio'], ['edicao','Formato &amp; corte'], ['audio-imagem','&Aacute;udio &amp; imagem'], ['privacidade','Privacidade']].map(([id, label]) => `<button type="button" data-category="${id}" aria-pressed="${id === 'all'}">${label}</button>`).join('')}</div>
<div class="guide-index">${guides.map((guide, index) => `<a class="guide-item" href="${guide.slug}/index.html" data-category="${guide.category}"><div class="guide-item-image"><img src="../_portal/guides/${guide.image}" alt="" width="160" height="112" loading="lazy"><span>${String(index + 1).padStart(2, '0')}</span></div><div><p class="guide-category">${guide.categoryLabel}</p><h2>${guide.title}</h2><p>${guide.summary}</p></div>${icon('../', 'arrow-up-right')}</a>`).join('')}</div><p id="guide-empty" role="status" hidden>Nenhum guia encontrado. <button type="button" id="guide-reset">Limpar filtros</button></p><p class="editorial-status">Textos elaborados por Codex (assistente de IA), com refer&ecirc;ncias t&eacute;cnicas e exemplos locais. Revis&atilde;o editorial humana pendente.</p></main>`;
write('guias/index.html', shell('Guias de v&iacute;deo', 'Guias de tamanho, formatos, corte, audio, imagens e metadados de video.', '/guias/', '../', hub, true));
console.log(JSON.stringify({ pages: guides.length + 1, images: assets.size, published: false }));
